# SPDX-License-Identifier: MIT
"""Dataset statistics, the dataset figures and the Color FERET attribute table.

Everything here is aggregate (counts and histograms), except the example montages
:func:`fig_examples`, which show dataset faces and must stay local (they are never
part of the repository).

Figures (file names of the paper, Section 3):

=====================  =========================================================
``ds_kk_imgs.png``     images per identity (from the index)
``ds_kk_filesize.png`` source file size (needs the raw AI-Solutions-KK download)
``ds_kk_dims.png``     source width / height of a seeded sample of 20 photos per
                       identity (raw download)
``ds_kk_age.png``      estimated age (``attributes.csv``)
``ds_kk_gender.png``   estimated gender (``attributes.csv``)
``ds_kk_mst.png``      Monk Skin Tone, one estimate per identity
``ds_kk_examples.png`` aligned-112 crops of 10 seeded identities (dataset faces)
=====================  =========================================================

Raw-photo statistics can be cached as JSON (:func:`raw_file_stats`,
``n_identities, n_images, per_id, sizes_kb, widths, heights``) and rendered from
the cache.
"""

from __future__ import annotations

import json
import logging
import os
import random
from collections.abc import Sequence
from pathlib import Path

import numpy as np
import pandas as pd

log = logging.getLogger(__name__)

#: Resolution of the saved dataset figures (dpi).
FIG_DPI = 120
#: Photos per identity sampled for the source-dimension histogram.
DIMS_PER_SUBJECT = 20
#: Seed of the photo sample and of the example-identity pick.
SEED = 0
#: Raw photo extensions counted by :func:`raw_file_stats`.
RAW_EXTS: tuple[str, ...] = (".jpg", ".jpeg", ".png", ".bmp", ".webp")

#: Attribute blocks of the Color FERET table: (labels column, heading).
CF_TABLE_ATTRS: tuple[tuple[str, str], ...] = (
    ("gender", "Gender"),
    ("race", "Race"),
    ("glasses", "Glasses"),
    ("pose", "Pose"),
)
#: First line (provenance comment) of the generated Color FERET table.
CF_TABLE_HEADER = "% generated by experiments/prepare/cf_attribute_table.py"
#: Provenance comment of the table as published in the paper; with it the generator
#: output is byte-identical to the paper's ``cf_attributes.tex``.
CF_TABLE_PAPER_HEADER = "% generated by generate_cf_attribute_table.py"


# --------------------------------------------------------------------- numbers
def index_summary(index: pd.DataFrame, pairs: pd.DataFrame | None = None) -> dict:
    """Aggregate counts of a dataset index (and, optionally, of its pairs)."""
    from face1kb.data.pairs import pair_counts  # noqa: PLC0415

    per = index.groupby(index["subject"].astype(str)).size()
    total, mated = pair_counts(index["subject"].astype(str))
    out = {
        "images": int(len(index)),
        "subjects": int(per.size),
        "images_per_subject": {
            "min": int(per.min()),
            "median": float(per.median()),
            "mean": round(float(per.mean()), 2),
            "max": int(per.max()),
        },
        "pairs": {"total": total, "mated": mated, "non_mated": total - mated},
    }
    if "pose" in index.columns:
        out["pose"] = {str(k): int(v) for k, v in index["pose"].value_counts().items()}
    if pairs is not None:
        n_m = int(pairs["label"].sum())
        out["pairs_file"] = {"total": int(len(pairs)), "mated": n_m}
    return out


def raw_file_stats(
    raw_dir: str | os.PathLike,
    dims_per_subject: int = DIMS_PER_SUBJECT,
    seed: int = SEED,
    exts: Sequence[str] = RAW_EXTS,
) -> dict:
    """Source-photo statistics of a folder-per-identity dataset.

    Counts the photos of every identity folder, their file sizes (kB) and the
    width/height of a seeded sample of ``dims_per_subject`` photos per identity
    (sorted listings and a dedicated ``random.Random(seed)``, so the sample does not
    depend on the file system).
    """
    from PIL import Image  # noqa: PLC0415

    raw_dir = Path(raw_dir)
    exts = tuple(e.lower() for e in exts)
    rng = random.Random(seed)
    ids = sorted(p.name for p in raw_dir.iterdir() if p.is_dir())
    per_id, sizes, widths, heights = [], [], [], []
    for ident in ids:
        files = sorted(
            p for p in (raw_dir / ident).iterdir() if p.suffix.lower() in exts
        )
        per_id.append(len(files))
        sizes.extend(p.stat().st_size / 1024.0 for p in files)
        for p in rng.sample(files, min(len(files), dims_per_subject)):
            try:
                with Image.open(p) as im:
                    widths.append(im.size[0])
                    heights.append(im.size[1])
            except OSError:
                log.warning("cannot read %s", p)
    return {
        "n_identities": len(ids),
        "n_images": int(sum(per_id)),
        "per_id": per_id,
        "sizes_kb": sizes,
        "widths": widths,
        "heights": heights,
    }


def save_json(obj: dict, path: str | os.PathLike) -> Path:
    """Write ``obj`` as JSON."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj))
    return path


# --------------------------------------------------------------------- figures
def _plt():
    import matplotlib  # noqa: PLC0415

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # noqa: PLC0415

    return plt


def _save(fig, path: str | os.PathLike) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=FIG_DPI, bbox_inches="tight")
    _plt().close(fig)
    return path


def fig_images_per_subject(
    per_id: Sequence[int], path, dataset_label="AI-Solutions-KK"
):
    """Histogram of images per identity."""
    plt = _plt()
    fig, ax = plt.subplots(figsize=(6, 3.2))
    ax.hist(per_id, bins=20, color="steelblue", edgecolor="white")
    ax.set_title(f"{dataset_label}: images per identity ({len(per_id)} IDs)")
    ax.set_xlabel("images")
    ax.set_ylabel("# identities")
    return _save(fig, path)


def fig_filesize(sizes_kb: Sequence[float], path, dataset_label="AI-Solutions-KK"):
    """Histogram of the source file sizes (kB, clipped at 120)."""
    plt = _plt()
    fig, ax = plt.subplots(figsize=(6, 3.2))
    ax.hist(np.clip(sizes_kb, 0, 120), bins=40, color="darkorange", edgecolor="white")
    med = np.median(sizes_kb)
    ax.axvline(med, color="k", ls="--", label=f"median {med:.1f} kB")
    ax.set_title(f"{dataset_label}: original (source) file size")
    ax.set_xlabel("KB (clipped 120)")
    ax.set_ylabel("# images")
    ax.legend()
    return _save(fig, path)


def fig_dims(widths, heights, path, dataset_label="AI-Solutions-KK"):
    """Histograms of the sampled source widths and heights."""
    plt = _plt()
    fig, ax = plt.subplots(1, 2, figsize=(9, 3.2))
    ax[0].hist(widths, bins=30, color="seagreen", edgecolor="white")
    ax[0].set_title("orig width (px)")
    ax[1].hist(heights, bins=30, color="teal", edgecolor="white")
    ax[1].set_title("orig height (px)")
    fig.suptitle(f"{dataset_label}: original image dimensions (sample)")
    fig.tight_layout(rect=[0, 0, 1, 0.88])
    return _save(fig, path)


def fig_age(ages: Sequence[int], path, dataset_label="AI-Solutions-KK"):
    """Histogram of the estimated ages (5-year bins)."""
    plt = _plt()
    fig, ax = plt.subplots(figsize=(6, 3.2))
    ax.hist(ages, bins=range(0, 90, 5), color="mediumpurple", edgecolor="white")
    ax.set_title(f"{dataset_label}: estimated age (n={len(ages)})")
    ax.set_xlabel("age (insightface genderage)")
    ax.set_ylabel("# images")
    return _save(fig, path)


def fig_gender(genders: Sequence[str], path, dataset_label="AI-Solutions-KK"):
    """Bar chart of the estimated genders."""
    plt = _plt()
    genders = list(genders)
    fig, ax = plt.subplots(figsize=(4, 3.2))
    ax.bar(
        ["F", "M"],
        [genders.count("F"), genders.count("M")],
        color=["palevioletred", "steelblue"],
    )
    ax.set_title(f"{dataset_label}: estimated gender (n={len(genders)})")
    ax.set_ylabel("# images")
    return _save(fig, path)


def fig_mst(mst_index: Sequence[int], path, dataset_label="AI-Solutions-KK"):
    """Bar chart of the Monk Skin Tone estimates (one per identity)."""
    from face1kb.data.attributes import MONK_PALETTE  # noqa: PLC0415

    plt = _plt()
    msts = [int(m) for m in mst_index]
    fig, ax = plt.subplots(figsize=(6, 3.2))
    ax.bar(
        range(1, 11),
        [msts.count(i) for i in range(1, 11)],
        color=list(MONK_PALETTE),
        edgecolor="gray",
    )
    ax.set_title(f"{dataset_label}: Monk Skin Tone (1 img/identity, n={len(msts)})")
    ax.set_xlabel("MST bin (1 light - 10 dark)")
    ax.set_ylabel("# identities")
    ax.set_xticks(range(1, 11))
    return _save(fig, path)


def pick_subjects(subjects: Sequence[str], n: int = 10, seed: int = SEED) -> list:
    """Seeded pick of ``n`` subjects from their sorted list."""
    return random.Random(seed).sample(sorted({str(s) for s in subjects}), n)


def fig_examples(
    crop_dir: str | os.PathLike,
    index: pd.DataFrame,
    path,
    title: str,
    n: int = 10,
    seed: int = SEED,
    strip_prefix: str = "pins_",
):
    """Montage of the first crop (index order) of ``n`` seeded subjects.

    The montage shows dataset faces; keep it out of any public repository.
    """
    from PIL import Image  # noqa: PLC0415

    plt = _plt()
    first = index.groupby(index["subject"].astype(str), sort=True)["rel_path"].first()
    pick = pick_subjects(first.index, n, seed)
    cols = 5
    rows = (n + cols - 1) // cols
    fig, ax = plt.subplots(rows, cols, figsize=(10, 2.1 * rows), squeeze=False)
    for a, subj in zip(ax.ravel(), pick):
        a.imshow(Image.open(Path(crop_dir) / first[subj]).convert("RGB"))
        a.axis("off")
        a.set_title(subj.removeprefix(strip_prefix)[:16], fontsize=7)
    for a in ax.ravel()[len(pick) :]:
        a.axis("off")
    fig.suptitle(title)
    return _save(fig, path)


def attribute_figures(attributes: pd.DataFrame, out_dir, prefix="ds_kk") -> list[Path]:
    """Age, gender and MST figures from an attribute table."""
    out_dir = Path(out_dir)
    ages = [int(a) for a in pd.to_numeric(attributes["age"], errors="coerce").dropna()]
    genders = [g for g in attributes["gender"].astype(str) if g in ("M", "F")]
    msts = pd.to_numeric(attributes["mst_index"], errors="coerce").dropna()
    return [
        fig_age(ages, out_dir / f"{prefix}_age.png"),
        fig_gender(genders, out_dir / f"{prefix}_gender.png"),
        fig_mst([int(m) for m in msts], out_dir / f"{prefix}_mst.png"),
    ]


def raw_figures(stats: dict, out_dir, prefix="ds_kk") -> list[Path]:
    """Source file-size and dimension figures from :func:`raw_file_stats`."""
    out_dir = Path(out_dir)
    return [
        fig_filesize(stats["sizes_kb"], out_dir / f"{prefix}_filesize.png"),
        fig_dims(stats["widths"], stats["heights"], out_dir / f"{prefix}_dims.png"),
    ]


# --------------------------------------------------------------------- CF table
def _esc(s: str) -> str:
    """Escape the LaTeX-active characters that occur in the label strings."""
    return str(s).replace("&", r"\&").replace("_", r"\_").replace("%", r"\%")


def cf_attribute_table(
    labels: pd.DataFrame,
    attrs: Sequence[tuple[str, str]] = CF_TABLE_ATTRS,
    header: str | None = CF_TABLE_HEADER,
) -> str:
    """Color FERET attribute distribution as a bare LaTeX ``tabular``.

    One block per attribute; each category with its image count and share of all
    rows of ``labels``, ordered by decreasing count (ties keep the order of
    ``pandas.Series.value_counts`` on the ``(subject, image)``-sorted table).
    """
    n = len(labels)
    lines = [header] if header else []
    lines += [
        "\\begin{tabular}{@{}lrr@{}}",
        "\\toprule",
        "Attribute & Images & \\% of corpus \\\\",
        "\\midrule",
    ]
    for i, (col, head) in enumerate(attrs):
        if col not in labels.columns:
            continue
        if i:
            lines.append("\\addlinespace[2pt]")
        lines.append(f"\\multicolumn{{3}}{{@{{}}l}}{{\\emph{{{head}}}}}\\\\")
        vc = labels[col].fillna("(unlabelled)").value_counts()
        for label, cnt in vc.items():
            lines.append(f"\\quad {_esc(label)} & {cnt:,} & {100 * cnt / n:.1f} \\\\")
    lines += [
        "\\midrule",
        f"\\textbf{{Total}} & \\textbf{{{n:,}}} & \\textbf{{100.0}} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
    ]
    return "\n".join(lines) + "\n"
