# SPDX-License-Identifier: MIT
"""End-to-end run of the data-preparation scripts on a synthetic Color FERET tree."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from face1kb import config

from ._nist import RECORDINGS, write_tree

cv2 = pytest.importorskip("cv2")

PREPARE = Path(__file__).resolve().parents[2] / "experiments" / "prepare"


def _script(name):
    spec = importlib.util.spec_from_file_location(
        f"prepare_{name}", PREPARE / f"{name}.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _crop(seed, size=224):
    rng = np.random.default_rng(seed)
    small = rng.integers(0, 256, (size // 16, size // 16, 3), dtype=np.uint8)
    return cv2.resize(small, (size, size), interpolation=cv2.INTER_CUBIC)


@pytest.fixture
def roots(tmp_path, monkeypatch):
    monkeypatch.setattr(config, "LAYOUT", "public")
    monkeypatch.setattr(config, "DATA_ROOT", tmp_path / "data")
    monkeypatch.setattr(config, "OUTPUT_ROOT", tmp_path / "outputs")
    d224 = config.aligned_dir("colorferet", 224)
    for k, (sid, img, *_) in enumerate(RECORDINGS):
        (d224 / sid).mkdir(parents=True, exist_ok=True)
        cv2.imwrite(str(d224 / sid / f"{img}.png"), _crop(k))
    write_tree(tmp_path / "nist")
    return tmp_path


def test_prepare_pipeline(roots):
    ds = "colorferet"
    rel = sorted(f"{sid}/{img}.png" for sid, img, *_ in RECORDINGS)

    # 112 px from the 224 px crops: an exact subsampling
    assert (
        _script("make_crop_variants").main(
            [
                "--dataset",
                ds,
                "--variants",
                "",
                "--resolutions",
                "112",
                "--workers",
                "1",
            ]
        )
        == 0
    )
    for rp in rel:
        a = cv2.imread(str(config.aligned_dir(ds, 224) / rp))
        b = cv2.imread(str(config.aligned_dir(ds, 112) / rp))
        assert np.array_equal(a[::2, ::2], b)

    assert _script("build_index").main(["--dataset", ds, "--check-res", "112,224"]) == 0
    index = config.read_index(ds)
    assert index.rel_path.tolist() == rel
    assert index.pose.tolist()[0] == "frontal image"

    assert _script("define_pairs").main(["--dataset", ds, "--sample"]) == 0
    pairs = pd.read_parquet(config.pairs_parquet(ds))
    assert pairs.label.tolist() == [1, 0, 0]
    assert (config.pairs_parquet(ds).parent / "pairs_sample.csv").is_file()

    assert (
        _script("prepare_colorferet_labels").main(["--nist", str(roots / "nist")]) == 0
    )
    labels = pd.read_csv(config.labels_csv(ds), dtype={"subject": str})
    assert labels.rel_path.tolist() == rel

    out = roots / "t.tex"
    assert _script("cf_attribute_table").main(["--out", str(out)]) == 0
    tex = out.read_text()
    assert tex.startswith("% generated by") and "\\quad male & 2 & 66.7" in tex

    assert (
        _script("make_crop_variants").main(
            ["--dataset", ds, "--resolutions", "56", "--workers", "1"]
        )
        == 0
    )
    for v in ("tight", "mid", "fill"):
        img = cv2.imread(str(config.aligned_dir(ds, 112, f"_{v}") / rel[0]))
        assert img.shape == (112, 112, 3)
    meta = json.loads((config.dataset_dir(ds) / "variants_templates.json").read_text())
    assert meta["source_resolution"] == 224 and set(meta["variants"]) == {
        "tight",
        "mid",
        "fill",
    }
    c56 = cv2.imread(str(config.aligned_dir(ds, 56) / rel[0]))
    c224 = cv2.imread(str(config.aligned_dir(ds, 224) / rel[0]))
    assert np.array_equal(c56, c224[::4, ::4])

    assert (
        _script("preprocess").main(
            ["--dataset", ds, "--ops", "A1,A3", "--workers", "1"]
        )
        == 0
    )
    assert (config.aligned_dir(ds, 112, "_A3") / rel[-1]).is_file()

    assert _script("dataset_report").main(["--dataset", ds]) == 0
    summary = json.loads(
        (config.output_dir("dataset_stats") / f"{ds}_summary.json").read_text()
    )
    assert summary["images"] == 3 and summary["pairs"]["mated"] == 1


def test_scripts_refuse_to_overwrite_or_write_into_legacy(roots, monkeypatch):
    build = _script("build_index")
    assert build.main(["--dataset", "colorferet", "--res", "224"]) == 0
    with pytest.raises(SystemExit, match="exists"):
        build.main(["--dataset", "colorferet", "--res", "224"])
    assert build.main(["--dataset", "colorferet", "--res", "224", "--overwrite"]) == 0
    pairs = _script("define_pairs")
    assert pairs.main(["--dataset", "colorferet", "--sample"]) == 0
    other = config.dataset_dir("colorferet") / "other_pairs.parquet"
    with pytest.raises(SystemExit, match="pairs_sample.csv exists"):
        pairs.main(["--dataset", "colorferet", "--sample", "--out", str(other)])
    (roots / "empty").mkdir()
    with pytest.raises(SystemExit, match="at most 3 levels below"):
        _script("prepare_colorferet_labels").main(["--nist", str(roots / "empty")])
    monkeypatch.setattr(config, "LAYOUT", "legacy")
    with pytest.raises(SystemExit, match="legacy"):
        build.main(["--dataset", "colorferet", "--res", "224"])
    with pytest.raises(SystemExit, match="legacy"):
        _script("preprocess").main(["--dataset", "colorferet"])


@pytest.fixture
def legacy_kk(tmp_path, monkeypatch):
    """A legacy-layout KK store whose index lists ``.jpg`` names for PNG crops."""
    monkeypatch.setattr(config, "LAYOUT", "legacy")
    monkeypatch.setattr(config, "DATA_ROOT", tmp_path / "datasets")
    monkeypatch.setattr(config, "OUTPUT_ROOT", tmp_path / "outputs")
    stems = ["pins_A B/A B0_0", "pins_A B/A B1_2", "pins_C/C0_0"]
    for k, stem in enumerate(stems):
        img = _crop(k)
        for res, crop in ((224, img), (112, img[::2, ::2])):
            p = config.aligned_dir("kk", res) / f"{stem}.png"
            p.parent.mkdir(parents=True, exist_ok=True)
            cv2.imwrite(str(p), crop)
    index = config.index_csv("kk")
    index.parent.mkdir(parents=True)
    index.write_text(
        "id,rel_path,identity,det_score,residual_px\n"
        + "".join(
            f"{k},{s}.jpg,{s.split('/')[0]},0.9,1.0\n" for k, s in enumerate(stems)
        )
    )
    return tmp_path, [f"{s}.png" for s in stems]


def test_legacy_kk_index_with_jpg_names(legacy_kk, monkeypatch):
    from face1kb.data import attributes

    root, rel = legacy_kk
    out = root / "out"
    args = ["--dataset", "kk", "--workers", "1", "--out-root", str(out)]
    assert _script("make_crop_variants").main([*args, "--variants", "tight"]) == 0
    assert all((out / "aligned_112_tight" / rp).is_file() for rp in rel)
    assert _script("preprocess").main([*args, "--ops", "A3", "--res", "224"]) == 0
    assert all((out / "aligned_224_A3" / rp).is_file() for rp in rel)

    class FakeGenderAge:
        def __init__(self, ctx_id=-1):
            pass

        def __call__(self, bgr):
            return 30, "F"

    monkeypatch.setattr(attributes, "GenderAge", FakeGenderAge)
    att = out / "attributes.csv"
    est = _script("estimate_attributes")
    assert est.main(["--dataset", "kk", "--no-mst", "--out", str(att)]) == 0
    df = pd.read_csv(att)
    assert df.rel_path.tolist() == rel and df.subject.tolist()[0] == "pins_A B"

    # unreadable crops: an error, and no output file
    (config.aligned_dir("kk", 112) / rel[1]).unlink()
    bad = out / "bad.csv"
    with pytest.raises(SystemExit, match="1 of 3 source crops"):
        est.main(["--dataset", "kk", "--no-mst", "--out", str(bad)])
    assert not bad.exists()
    with pytest.raises(SystemExit, match="1 of 3 source crops could not be read"):
        _script("make_crop_variants").main(
            [*args, "--variants", "mid", "--src-res", "112"]
        )
    with pytest.raises(SystemExit, match="not found"):
        _script("preprocess").main([*args, "--ops", "A3", "--res", "96"])


def test_rederive_112_needs_overwrite(roots, caplog):
    ds = "colorferet"
    rel = sorted(f"{sid}/{img}.png" for sid, img, *_ in RECORDINGS)
    d112, d224 = config.aligned_dir(ds, 112), config.aligned_dir(ds, 224)
    for k, rp in enumerate(rel):  # 112 px crops of "another alignment"
        (d112 / rp).parent.mkdir(parents=True, exist_ok=True)
        cv2.imwrite(str(d112 / rp), _crop(50 + k, 112))
    mk = _script("make_crop_variants")
    args = ["--dataset", ds, "--variants", "", "--resolutions", "112", "--workers", "1"]
    with caplog.at_level("INFO"):
        assert mk.main(args) == 0
    assert "nothing written, all 3 outputs exist" in caplog.text
    assert not np.array_equal(
        cv2.imread(str(d224 / rel[0]))[::2, ::2], cv2.imread(str(d112 / rel[0]))
    )
    assert mk.main([*args, "--overwrite"]) == 0
    for rp in rel:
        assert np.array_equal(
            cv2.imread(str(d224 / rp))[::2, ::2], cv2.imread(str(d112 / rp))
        )
